apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: inventory-orchestrator
build:
  artifacts:
  - image: dfdsdk/inventory-orchestrator
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
