apiVersion: batch/v1
kind: CronJob
metadata:
  name: aws-inventory-orchestrator
  namespace: inventory
spec:
  schedule: $(CRON_SCHEDULE)
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: aws-inventory-orchestrator-sa
          containers:
            - image: dfdsdk/aws-inventory-orchestrator:latest
              name: orchestrator
              args:
              - $(INCLUDE_ACCOUNTS)
          restartPolicy: OnFailure
