resources:
  - serviceaccount.yaml
  - cronjob.yaml
  - role.yaml
  - rolebinding.yaml

vars:
  - name: BILLING_ACCOUNT_ID
    objref:
      kind: ConfigMap
      name: environment
      apiVersion: v1
    fieldref:
      fieldpath: data.BILLING_ACCOUNT_ID
  - name: INVENTORY_ORCHESTRATOR_ROLE
    objref:
      kind: ConfigMap
      name: environment
      apiVersion: v1
    fieldref:
      fieldpath: data.INVENTORY_ORCHESTRATOR_ROLE
  - name: RUNNER_ACCOUNT_ID
    objref:
      kind: ConfigMap
      name: environment
      apiVersion: v1
    fieldref:
      fieldpath: data.RUNNER_ACCOUNT_ID
  - name: INVENTORY_RUNNER_ROLE
    objref:
      kind: ConfigMap
      name: environment
      apiVersion: v1
    fieldref:
      fieldpath: data.INVENTORY_RUNNER_ROLE
  - name: CRON_SCHEDULE
    objref:
      kind: ConfigMap
      name: environment
      apiVersion: v1
    fieldref:
      fieldpath: data.CRON_SCHEDULE
  - name: INCLUDE_ACCOUNTS
    objref:
      kind: ConfigMap
      name: environment
      apiVersion: v1
    fieldref:
      fieldpath: data.INCLUDE_ACCOUNTS
  - name: INVENTORY_BUCKET_NAME
    objref:
      kind: ConfigMap
      name: environment
      apiVersion: v1
    fieldref:
      fieldpath: data.INVENTORY_BUCKET_NAME

configMapGenerator:
  - name: environment
    envs: [vars.env]

configurations:
  - env-var-transformer.yaml
