resources:
  - serviceaccount.yaml
  - cronjob.yaml
  - role.yaml
  - rolebinding.yaml

vars:
  - name: ORCHESTRATOR_ROLE_ARN
    objref:
      kind: ConfigMap
      name: environment
      apiVersion: v1
    fieldref:
      fieldpath: data.ORCHESTRATOR_ROLE_ARN
  - name: RUNNER_ROLE_ARN
    objref:
      kind: ConfigMap
      name: environment
      apiVersion: v1
    fieldref:
      fieldpath: data.RUNNER_ROLE_ARN
  - name: CRON_SCHEDULE
    objref:
      kind: ConfigMap
      name: environment
      apiVersion: v1
    fieldref:
      fieldpath: data.CRON_SCHEDULE
  - name: INCLUDE_ACCOUNTS
    objref:
      kind: ConfigMap
      name: environment
      apiVersion: v1
    fieldref:
      fieldpath: data.INCLUDE_ACCOUNTS
  - name: S3_BUCKET
    objref:
      kind: ConfigMap
      name: environment
      apiVersion: v1
    fieldref:
      fieldpath: data.S3_BUCKET

configMapGenerator:
  - name: environment
    envs: [vars.env]

configurations:
  - env-var-transformer.yaml
