apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: inventory-orchestrator
  namespace: inventory
subjects:
  - kind: ServiceAccount
    name: aws-inventory-orchestrator-sa
    namespace: inventory
#  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: inventory-orchestrator # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
