apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: inventory
  name: inventory-orchestrator
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
