apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: inventory
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["jobs"]
  verbs: ["create"]
