apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-orchestrator-sa
  namespace: inventory
  annotations:
    eks.amazonaws.com/role-arn: $(ROLE_ARN)
    eks.amazonaws.com/sts-regional-endpoints: "true"