---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-inventory-orchestrator-sa
  namespace: inventory
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::$(BILLING_ACCOUNT_ID):role/$(INVENTORY_ORCHESTRATOR_ROLE)"
    eks.amazonaws.com/sts-regional-endpoints: "true"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-inventory-runner-sa
  namespace: inventory
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::$(RUNNER_ACCOUNT_ID):role/$(INVENTORY_RUNNER_ROLE)"
    eks.amazonaws.com/sts-regional-endpoints: "true"
